# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csugrads/musik013/cs5631/Labs/lab6/v2/myalloc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csugrads/musik013/cs5631/Labs/lab6/v2/myalloc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csugrads/musik013/cs5631/Labs/lab6/v2/myalloc/CMakeFiles /home/csugrads/musik013/cs5631/Labs/lab6/v2/myalloc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csugrads/musik013/cs5631/Labs/lab6/v2/myalloc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named alligator

# Build rule for target.
alligator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alligator
.PHONY : alligator

# fast build rule for target.
alligator/fast:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/build
.PHONY : alligator/fast

alligator.o: alligator.c.o

.PHONY : alligator.o

# target to build an object file
alligator.c.o:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/alligator.c.o
.PHONY : alligator.c.o

alligator.i: alligator.c.i

.PHONY : alligator.i

# target to preprocess a source file
alligator.c.i:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/alligator.c.i
.PHONY : alligator.c.i

alligator.s: alligator.c.s

.PHONY : alligator.s

# target to generate assembly for a file
alligator.c.s:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/alligator.c.s
.PHONY : alligator.c.s

myalloc.o: myalloc.c.o

.PHONY : myalloc.o

# target to build an object file
myalloc.c.o:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/myalloc.c.o
.PHONY : myalloc.c.o

myalloc.i: myalloc.c.i

.PHONY : myalloc.i

# target to preprocess a source file
myalloc.c.i:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/myalloc.c.i
.PHONY : myalloc.c.i

myalloc.s: myalloc.c.s

.PHONY : myalloc.s

# target to generate assembly for a file
myalloc.c.s:
	$(MAKE) -f CMakeFiles/alligator.dir/build.make CMakeFiles/alligator.dir/myalloc.c.s
.PHONY : myalloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alligator"
	@echo "... alligator.o"
	@echo "... alligator.i"
	@echo "... alligator.s"
	@echo "... myalloc.o"
	@echo "... myalloc.i"
	@echo "... myalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

